# Generated by Django 4.0.4 on 2022-07-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('string', models.CharField(choices=[('Co', 'Confidential'), ('Lu', 'Luxilon Alu Power'), ('Gr', 'Grapple Snake')], default='Co', max_length=20)),
            ],
        ),
    ]
