# Generated by Django 4.0.4 on 2022-07-21 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_restring'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restring',
        ),
    ]
