# Generated by Django 4.0.4 on 2022-07-21 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_delete_restring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('string', models.CharField(choices=[('C', 'Confidential'), ('L', 'Luxilon Alu Power'), ('G', 'Grapple Snake')], default='C', max_length=20)),
                ('racquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.racquet')),
            ],
        ),
    ]
