# Generated by Django 4.0.4 on 2022-07-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_restring'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='restring',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='restring',
            name='date',
            field=models.DateField(verbose_name='Restring Date'),
        ),
    ]
