# Generated by Django 4.0.4 on 2022-07-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_user_alter_restring_options_alter_restring_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='racquet',
            name='users',
            field=models.ManyToManyField(to='main_app.user'),
        ),
    ]
